# 显著性标签

```{r}
# Calculate annotation
anno <- t.test(
  iris[iris$Petal.Width > 1 & iris$Species == "versicolor", "Sepal.Width"],
  iris[iris$Species == "virginica", "Sepal.Width"]
)$p.value


p <- ggplot(iris, aes(x = Species, y = Sepal.Width, fill = Petal.Width > 1)) +
  geom_boxplot(position = "dodge")


p
```

```{r}
ggbuild <- ggplot_build(p)
fill_data <- ggbuild$data[[1]]

fill_data$x
fill_data$ymax_final
```

## `annotate()`

```{r}
p + 
    annotate(geom = "segment", x = x[3], xend = x[4],
             y = 4.05)+
    annotate(geom = "segment", x = x[3], y = 3.6,yend = 4.05
             )+
    annotate(geom = "segment", x = x[4], y = 3.9,yend = 4.05
             )+
    annotate(geom = "text", x = (x[3]+x[4])/2, y = 4.15,
             label= str_glue("p = {anno %>% round(4)}")
                )
```

## [ggsignif](https://const-ae.github.io/ggsignif/index.html)

```{r}
library(ggsignif)

# Make plot with custom x and y position of the bracket
p +
  geom_signif(
    annotation = formatC(anno, digits = 3),
    y_position = 4.05, xmin = 2.2, xmax = 3,
    tip_length = c(0.2, 0.04)
  )



```
