# 点图

## 散点图

```{r}
p <- ggplot(data = mpg, aes(x = cty, y = hwy))+
    geom_point()
p
```

### 添加拟合曲线和曲线方程

```{r}
library(ggpmisc)
p+
  stat_correlation(mapping = use_label("r", "t", "p")) +
  geom_point()+
    stat_poly_line(formula = y ~x)
```

R^2^ ,p值

```{r}

p + 
    geom_smooth(method = "lm",formula = "y~x",color="blue",linewidth=.5)+
    stat_poly_eq(mapping = use_label(c("eq", "adj.R2","F")), 
                 formula = y ~ x
                )



```

## 列点图

### `geom_dotplot()`

```{r}
ToothGrowth$dose <- as.factor(ToothGrowth$dose)
# 点图
p1 <- ggplot(ToothGrowth, aes(x=dose, y=len)) + 
  geom_dotplot(binaxis='y', stackdir='center',
               stackratio=1.5, dotsize=1.2)


# 旋转
p2 <- p1 + coord_flip()

# 添加摘要统计信息 stat_summary()
p3 <- p1 + stat_summary(fun=mean, geom="point", shape=18,
                 size=3, color="red")

p4<- p1 + stat_summary(fun=median, geom="point", shape=18,
                 size=3, color="red")

library(patchwork)
(p1+p2)/(p3+p4)
```

### `ggpubr::ggdotplot()`

```{r}
library(ggpubr)
library(readxl)
f6d <-
    read_excel("data/01source.xlsx", sheet = "Fig.6", range = "D2:E18")
f6d |> pivot_longer(
    cols = everything(),
    names_to = "status",
    values_to = "Ratio",
) |> 
    tidyr::drop_na() ->f6d
```

```{r}
ggdotplot(f6d,
          x="status",
          y="Ratio",
          add =c("mean_sd"),
          color = "status",
          fill = "status",
          error.plot = "errorbar",
)+
    geom_signif(
        comparisons = list(c("relapse","non-relapse")),
    )+
    
    stat_summary(
        fun.data = "mean_sd",geom = "pointrange",width=.3
    )+
    ggplot2::annotate(
        geom="segment",
        x=0.9,
        xend=1.1,
        y=2.42019873,#均值
    )+
    ggplot2::annotate(
        geom="segment",
        x=1.9,
        xend=2.1,
        y=0.789463173,#均值
    )

```

## [蜂群图](https://github.com/eclarke/ggbeeswarm)

Beeswarm plots

```{r}
if(!require(ggbeeswarm)) install.packages('ggbeeswarm')
```

```{r}
set.seed(12345)
#compare to jitter
ggplot(iris, aes(Species, Sepal.Length)) + geom_jitter() |
    ggplot(iris, aes(Species, Sepal.Length)) + geom_quasirandom(varwidth = TRUE) |
    ggplot(iris, aes(Species, Sepal.Length)) + geom_beeswarm() + ggtitle("Beeswarm")
```
