# 生存曲线

## Kaplan-Meier curve

```{r}
library(tidyverse)
library(readxl)
library(survival)
library(ggsci)
library(ggsurvfit)
```

```{r}
### 数据 三列 “group”分组列， “time”生存时间列，“status”事件状态列
d<-read_excel("data/01source.xlsx",sheet=1,range = "A19:E75") |> 
    rename(
        LR_DPVB=`LR-DPVB`
    )  |> 
    pivot_longer(
        cols = CON:LR_DPVB,
        names_to = "treatment",
        values_to = "status"
    ) |> drop_na() |> 
    mutate(
        treatment=factor(treatment,levels=c('CON','LDRT','DPVB','LR_DPVB'))
    )
# 加载包
d
# 使用 Kaplan-Meier 方法拟合生存曲线
km_fit<-survfit2(Surv(Days,status)~treatment,data=d)
summary(km_fit)
```

## `plot()`

```{r}
plot(km_fit,
     lty = 1,
     col = c("gray","blue","orange3","darkred"),
     lwd = 2,
)
```

## `survminer::ggsurvplot()`

```{r}
# 使用 ggplot2 和 survminer 绘制生存曲线图
library(survminer)
p <- ggsurvplot(
    fit  = km_fit,
    data = d,
    fun = "pct",  #event',累计死亡比列，'cumhaz':cumulative hazard累计风险
    
    palette = "jco",
    linetype = c(1,5,4,6),
    surv.median.line = 'none',
    
    conf.int = F,

    
    pval = TRUE,# "log rank p=0.0053"
    log.rank.weights='1',  
    pval.method = TRUE,
    pval.coord=c(40,75),
    pval.method.coord=c(32,75),
    
    risk.table = "abs_pct", # "nrisk_cumcensor" and "nrisk_cumevents"
    risk.table.col = "treatment",
    risk.table.height=0.3,
    tables.theme = theme_cleantable(),
    ncensor.plot=T,
  
    
    axes.offset=F,  #(0,0)pos
    title = "Hepa1-6 tumor",
    xlab="Days",
    ylab="Percent survival (%)",
    
    legend.title = "",
    legend = c(0.2,0.35),
    legend.labs=c('CON','LDRT','DPVB','LR_DPVB'),
    
    ggtheme = theme_survminer(),
)
p
```


```{r}
fit<- survfit(Surv(time, status) ~ sex, data = lung)

# Basic survival curves
ggsurvplot(fit, data = lung)

# Customized survival curves
p <- ggsurvplot(fit, data = lung,
           surv.median.line = "hv", # Add medians survival
           
           # Change legends: title & labels
           legend.title = "Sex",
           legend.labs = c("Male", "Female"),
           # Add p-value and tervals
           pval = TRUE,
           
           conf.int = TRUE,
           # Add risk table
           risk.table = TRUE,
           tables.height = 0.2,
           tables.theme = theme_cleantable(),
           
           # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
           # or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
           palette = c("#E7B800", "#2E9FDF"),
           ggtheme = theme_bw() # Change ggplot2 theme
)
```


```{r}
p <- ggsurvplot(fit, data = lung,
                surv.median.line = "hv", # Add medians survival
                
                # Change legends: title & labels
                legend.title = "Sex",
                legend.labs = c("Male", "Female"),
                # Add p-value and tervals
                pval = F,    ##不默认显示P
                conf.int = TRUE,
                # Add risk table
                risk.table = TRUE,
                tables.height = 0.2,
                tables.theme = theme_cleantable(),
                
                # Color palettes. Use custom color: c("#E7B800", "#2E9FDF"),
                # or brewer color (e.g.: "Dark2"), or ggsci color (e.g.: "jco")
                palette = c("#E7B800", "#2E9FDF"),
                ggtheme = theme_bw() # Change ggplot2 theme
)
##计算公式
data.survdiff <- survdiff(Surv(time, status) ~ sex,data = lung)
p.val = 1 - pchisq(data.survdiff$chisq, length(data.survdiff$n) - 1)
HR = (data.survdiff$obs[2]/data.survdiff$exp[2])/(data.survdiff$obs[1]/data.survdiff$exp[1])
up95 = exp(log(HR) + qnorm(0.975)*sqrt(1/data.survdiff$exp[2]+1/data.survdiff$exp[1]))
low95 = exp(log(HR) - qnorm(0.975)*sqrt(1/data.survdiff$exp[2]+1/data.survdiff$exp[1]))
ci <- paste0(sprintf("%.3f",HR)," [",sprintf("%.3f",low95),", ",sprintf("%.3f",up95),"]")

p$plot <- p$plot + 
  annotate("text", x = 0, y = 0.05, 
                            label = paste0("P value = ",sprintf("%.3f",p.val),"\n HR (95% CI) = ",ci),   ###添加P和HR 95%CI
                            size = 5, color = "black", hjust = 0)+
  theme(text = element_text(size = 15))
p$plot
```




## ggsurvfit

```{r}
library(ggsurvfit)
km_fit


km_fit |> tidy_survfit() |> 
    ggplot(aes(time,estimate,min=conf.low,ymax=conf.low,
               color=strata,fill=strata))+
    scale_color_jco()+
    geom_step()

km_fit |> ggsurvfit()+
    add_confidence_interval()+
    # 添加删失点
    add_censor_mark()  +
    add_quantile()+
    add_pvalue("annotation",size=3,x=5,y=0.25)+
    #add_pvalue(caption = "Log-rank {p.value}")+
    add_risktable(size = 3,risktable_height = 0.3)+
    add_legend_title("treatment")
```




