# 误差棒图

## errorbar

```{r}
corr_res <- map(mtcars %>% select(-mpg), cor.test, y = mtcars$mpg)
library(broom)

corr_res %>% 
    map_dfr(tidy, .id = "predictor") %>% 
    ggplot(aes(x = fct_reorder(predictor, estimate))) + 
    geom_point(aes(y = estimate)) + 
    geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = .1) +
    labs(x = NULL, y = "Correlation with mpg")

```

## linerange

```{r}
corr_res %>% 
    map_dfr(tidy, .id = "predictor") %>% 
    ggplot(aes(x = fct_reorder(predictor, estimate))) + 
    geom_point(aes(y = estimate)) + 
    geom_linerange(aes(ymin = conf.low, ymax = conf.high)) +
    labs(x = NULL, y = "Correlation with mpg")
```

## pointrange

```{r}
corr_res %>% 
    map_dfr(tidy, .id = "predictor") %>% 
    ggplot(aes(x = fct_reorder(predictor, estimate))) + 
    geom_pointrange(aes(y = estimate, ymin = conf.low, ymax = conf.high)) +
    labs(x = NULL, y = "Correlation with mpg")
```

## crossbar

```{r}
corr_res %>% 
    map_dfr(tidy, .id = "predictor") %>% 
    ggplot(aes(x = fct_reorder(predictor, estimate))) + 
    geom_crossbar(aes(y = estimate, ymin = conf.low, ymax = conf.high)) +
    labs(x = NULL, y = "Correlation with mpg")
```

## 
